### ISSUE TITLE
Temp Perk

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/AdvancedPerks#1]
Can you add perk permission like only available for 12 hours? It will be great!

**Comment by Mundschutziii** [comment]
Do you mean that a Perk is only available in the ui for 12 hours?

**Comment by good777LUCKY** [comment]
yes

**Comment by good777LUCKY** [comment]
Like this perk is only available for 12 hours and when timeout the perk's permission will be removed from the player.

**Comment by Mundschutziii** [comment]
You can do this with a permission system like Luck Perms.
Set timed permissions for a player or group.

**Comment by good777LUCKY** [comment]
> You can do this with a permission system like Luck Perms.
> Set timed permissions for a player or group.

It will be more convenient and helpful for who don't use LuckPerms.

**Comment by Mundschutziii** [comment]
Maybe I'll add that, but not yet.
